# Site settings
title: Mai Nhật Duy
description: Personal blog and portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mainhatduy.github.io" # the base hostname & protocol for your site
logo: /assets/img/avt.jpg # your profile picture

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Pagination settings
paginate: 10
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Author information
author:
  name: Mai Nhật Duy
  email: your.email@example.com
  github: mainhatduy

# SEO settings
lang: vi
locale: vi_VN

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

