# Site settings
title: Mai Nhật Duy
description: Personal blog and portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mainhatduy.github.io" # the base hostname & protocol for your site
logo: /assets/img/avt.jpg # your profile picture
permalink: /:title/
# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Pagination settings
paginate: 10
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Author information
author:
  name: Mai Nhật Duy
  email: maiduy07102003@gmail.com
  github: mainhatduy

# Social links
social:
  github: mainhatduy
  email: maiduy07102003@gmail.com
  huggingface: myduy

# SEO settings
lang: vi
locale: vi_VN

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

